package battleBusDriver.fortniteTools;

public enum FortniteStatType {
	SOLO_TOP10, SOLO_TOP25, DUO_TOP5, DUO_TOP12, SQUAD_TOP3, SQUAD_TOP6,
	SOLO_KILLS, DUO_KILLS, SQUAD_KILLS, TOTAL_KILLS,
	SOLO_MINUTES_PLAYED, DUO_MINUTES_PLAYED, SQUAD_MINUTES_PLAYED, TOTAL_MINUTES_PLAYED,
	SOLO_WINS, DUO_WINS, SQUAD_WINS, TOTAL_WINS,
	SOLO_MATCHES_PLAYED, DUO_MATCHES_PLAYED, SQUAD_MATCHES_PLAYED, TOTAL_MATCHES_PLAYED,
	SOLO_SCORE, DUO_SCORE, SQUAD_SCORE,
	SOLO_KD, DUO_KD, SQUAD_KD, TOTAL_KD,
	SOLO_WIN_RATE, DUO_WIN_RATE, SQUAD_WIN_RATE, TOTAL_WIN_RATE,
	SOLO_KILLS_PER_MINUTE, DUO_KILLS_PER_MINUTE, SQUAD_KILLS_PER_MINUTE, TOTAL_KILLS_PER_MINUTE,
	SOLO_KILLS_PER_MATCH, DUO_KILLS_PER_MATCH, SQUAD_KILLS_PER_MATCH, TOTAL_KILLS_PER_MATCH
}
